### ISSUE TITLE
Feature Request: Expose parsing of individual domain without local part

### ISSUE THREAD

**Issue by the-eater** [mathematic-inc/addr-spec-rs#84]
It would be nice if we could parse an individual domain without the localpart. 

Especially since with SMTP the `EHLO` and `HELO` commands have an argument which is only the domain that has to be spec compliant, and this crate has all the logic already.

**Comment by jrandolf** [comment]
The point of this crate is to parse email addresses. If you need to parse domains, I'd recommend looking for a crate that does that. In practice, this shouldn't matter; you generally have bigger fish to fry.
